oom-ai/oomstore

- internal/database/offline/postgres/import.go
- internal/database/offline/test_impl/import.go
- internal/database/offline/test_impl/util.go
- internal/database/offline/types.go
- pkg/oomstore/import.go
This PR does:
- remove `GroupName` from `ImportOpt` because data_table is now named as `data_<group_id>_<revision_id>`
- avoid rename in `Import` because `DataTableName` is already generated before import
- update callers of offline method `Import`
> Jinghan/remove GroupName from ImportOpt

- featctl/cmd/register_batch_feature.go
- internal/database/metadata/postgres/feature.go
- internal/database/metadata/test_impl/feature.go
- internal/database/metadata/types.go
- pkg/oomstore/feature.go
- pkg/oomstore/feature_test.go
- pkg/oomstore/types/options.go
Currently, `types.CreateFeatureOpt` is not used in codebase, while `metadata.CreateFeatureOpt` is used in `database`, `oomstore` and `featctl`.
This PR embeds `types.CreateFeatureOpt` to `metadata.CreateFeatureOpt`, so that `metadata.CreateFeatureOpt` is only used in `database`, while `types.CreateFeatureOpt` used in `oomstore` and `featctl`.
> Jinghan/embed types.CreateFeatureOpt to metadata.CreateFeatureOpt

- featctl/cmd/update_feature.go
- pkg/oomstore/feature.go
This PR separates the usages of `types.UpdateFeatureOpt` and `metadata.UpdateFeatureOpt`:
- `metadata.UpdateFeatureOpt`: used in `internal/database`
- `types.UpdateFeatureOpt`: used in `pkg/oomstore` and `featctl`
> Jinghan/separate types.UpdateFeatureOpt and metadata.UpdateFeatureOpt

- featctl/cmd/join_historical_feature_helper.go
- featctl/cmd/list_feature.go
- pkg/oomstore/export.go
- pkg/oomstore/export_test.go
- pkg/oomstore/feature.go
- pkg/oomstore/sync.go
- pkg/oomstore/sync_test.go
- pkg/oomstore/types/options.go
This PR does:
- `types.ListFeatureOpt`: used in `pkg/oomstore` and `featctl`
- `metadata.ListFeatureOpt`: used in `internal/database`.
> Jinghan/separate types.ListFeatureOpt and metadata.ListFeatureOpt

- featctl/cmd/register_entity.go
- featctl/cmd/update_entity.go
- internal/database/metadata/postgres/entity.go
- internal/database/metadata/test_impl/entity.go
- internal/database/metadata/test_impl/feature.go
- internal/database/metadata/test_impl/feature_group.go
- internal/database/metadata/test_impl/revision.go
- internal/database/metadata/types.go
- pkg/oomstore/entity.go
- pkg/oomstore/types/options.go
This PR does:
- separate `types.CreateEntityOpt` and `metadata.CreateEntityOpt`
- separate `types.UpdateEntityOpt` and `metadata.UpdateEntityOpt`
> Jinghan/use types.CreateEntityOpt and types.UpdateEntityOpt in oomstore

- featctl/cmd/join_historical_feature_helper.go
- featctl/cmd/sync.go
- internal/database/metadata/postgres/db.go
- internal/database/metadata/postgres/entity.go
- internal/database/metadata/postgres/feature.go
- internal/database/metadata/postgres/feature_group.go
- internal/database/metadata/postgres/revision.go
- internal/database/metadata/test_impl/feature_group.go
- internal/database/metadata/test_impl/revision.go
- internal/database/online/postgres/import.go
- internal/database/online/redis/get.go
- internal/database/online/redis/import.go
- internal/database/online/redis/util.go
- pkg/oomstore/join_test.go
- pkg/oomstore/online_query.go
- pkg/oomstore/online_query_test.go
- pkg/oomstore/sync.go
- pkg/oomstore/sync_test.go
- pkg/oomstore/types/feature.go
- pkg/oomstore/types/options.go
This pr changes `Id` into `ID` everywhere.
Close #502
> refactor: unify id spelling

- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/postgres/database.go
- internal/database/metadata/postgres/db.go
- internal/database/metadata/store.go
Tx does not guarantee that GetXXX and ListXXX are in the transaction, because we Get and List via Informer rather than via DB. so it removes them
> fix(metastore/postgres): remove GetXXX and ListXXX from Tx

- featctl/cmd/register_group.go
- featctl/cmd/update_group.go
- internal/database/metadata/postgres/feature_group.go
- internal/database/metadata/test_impl/feature.go
- internal/database/metadata/test_impl/feature_group.go
- internal/database/metadata/test_impl/revision.go
- internal/database/metadata/types.go
- pkg/oomstore/feature_group.go
- pkg/oomstore/types/options.go
This PR does:
- separate `types.CreateFeatureGroupOpt` and `metadata.CreateFeatureGroupOpt`
- separate `types.UpdateFeatureGroupOpt` and `metadata.UpdateFeatureGroupOpt`
> Jinghan/use types.CreateFeatureGroupOpt and types.UpdateFeatureGroupOpt in oomstore #506

- internal/database/metadata/test_impl/revision.go
- internal/database/metadata/types.go
- pkg/oomstore/types/options.go
This PR removes `metadata.GetRevisionOpt` and `types.GetRevisionOpt`.
> Jinghan/remove GetRevisionOpt

- internal/database/metadata/informer/informer.go
- internal/database/metadata/informer/revision.go
- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/revision.go
- internal/database/metadata/types.go
- pkg/oomstore/join.go
- pkg/oomstore/join_test.go
- pkg/oomstore/revision.go
This pr simplifies `ListRevisionOpt` since we actually never use `DataTables` to filter revisions.
> refactor: simplify list revision opt

- internal/database/metadata/postgres/revision.go
- internal/database/metadata/test_impl/revision.go
- internal/database/offline/test_impl/export.go
- internal/database/offline/test_impl/import.go
- internal/database/offline/test_impl/join.go
- internal/database/online/postgres/get.go
- internal/database/online/postgres/import.go
- internal/database/online/postgres/purge.go
- pkg/oomstore/import_test.go
This PR does:
- rename offline data_table name to `offline_<group_id>_<revision_id>`
- rename online postgres data_table name to `online_<revision_id>`
> Jinghan/rename offline and online data_table name

- featctl/cmd/register_batch_feature.go
- internal/database/metadata/test_impl/feature.go
- internal/database/metadata/types.go
- pkg/oomstore/feature.go
- pkg/oomstore/feature_test.go
- pkg/oomstore/types/options.go
This PR refactors `types.CreateGroupOpt`:
- changes field `GroupID` to `GroupName`
- use `GroupID` in database layer, while `GroupName` in oomstore and featctl
> Jinghan/refactor types.CreateGroupOpt

- featctl/cmd/join_helper.go
- pkg/oomstore/export_test.go
- pkg/oomstore/import_test.go
- pkg/oomstore/join.go
- pkg/oomstore/join_test.go
- pkg/oomstore/online_query.go
- pkg/oomstore/online_query_test.go
- pkg/oomstore/types/options.go
This PR does:
- refactor `types.OnlineMultiGetOpt`: replace field `FeatureIDs` by `FeatureNames`
- refactor `types.JoinOpt`: replace field `FeatureIDs` by `FeatureNames`
- shorten oomstore unit test name
> Jinghan/use FeatureNames in JoinOpt and OnlineMultiGetOpt

- featctl/cmd/import.go
- pkg/oomstore/import.go
- pkg/oomstore/import_test.go
- pkg/oomstore/types/options.go
This PR refactors `types.ImportOpt`: changes field `GroupID` to `GroupName`.
> Jinghan/change ImportOpt.GroupID to ImportOpt.GroupName

- internal/database/offline/postgres/join.go
`dropTemporaryTables` should be executed after all rows have been read.
> fix(database): remove unnecessary dropTemporaryTables

- pkg/errdefs/defs.go
- pkg/errdefs/helper.go
- pkg/errdefs/helper_test.go
- pkg/errdefs/is.go
This PR adds a mechanism for handling errors, which is responsible for defining the type of error in the oomstore and providing a way to check the error type.
This is an example for apply：
```go
func (f *Informer) GetEntityByName(ctx context.Context, name string) (*types.Entity, error) {
if entity := f.Cache().Entities.Find(func(e *types.Entity) bool {
return e.Name == name
}); entity == nil {
return nil, errdefs.NotFound(fmt.Errorf("feature entity '%s' not found", name))
} else {
return entity.Copy(), nil
}
}
---
func (s *OomStore) applyEntity(ctx context.Context, txStore metadata.WriteStore, newEntity apply.Entity) (int, error) {
entityExist := true
entity, err := s.metadata.GetEntityByName(ctx, newEntity.Name)
if err != nil {
if !errdefs.IsNotFound(err) {
return 0, err
}
entityExist = …
```
> feat(errdefs): Add error mechanism for oomstore

- pkg/oomstore/online_query.go
- pkg/oomstore/online_query_test.go
- pkg/oomstore/types/types.go
This PR refactors oomstore API `OnlineMultiGet`:
- change return type to `map[string]*types.FeatureValues`
- modify corresponding unit test `TestOnlineMultiGet`
> Jinghan/refactor return type of API OnlineMultiGet

- featctl/cmd/join_helper.go
- go.sum
- pkg/oomstore/join.go
- pkg/oomstore/types/options.go
This PR implements oomstore API `JoinByFile`, which takes in `InputFilePath` and `OutputFilePath` as arguments, writes results to file.
> Jinghan/implement oomstore API JoinByFile

- Makefile
The existing `sed` command doesn't run on linux, thus failing the ci.
Use perl instead for better os portability
https://stackoverflow.com/a/22247781/7550592
> fix: replace sed with perl for os portability

- oomd/main.go
- oomd/root.go
- oomd/server.go
This PR adds a configuration system to oomd so that oomd can initialise the oomstore using configuration files and environment variables like featctl.
It also makes it easier for python to start oomd
relate #582
> feat(oomd): adding a configuration system

- pkg/oomstore/apply.go
- pkg/oomstore/entity.go
- pkg/oomstore/export.go
- pkg/oomstore/export_test.go
- pkg/oomstore/feature.go
- pkg/oomstore/feature_test.go
- pkg/oomstore/group.go
- pkg/oomstore/import.go
- pkg/oomstore/import_test.go
- pkg/oomstore/join.go
- pkg/oomstore/join_test.go
- pkg/oomstore/online_query.go
- pkg/oomstore/revision.go
- pkg/oomstore/sync.go
- pkg/oomstore/sync_test.go
This PR does:
- refresh informer at the beginning of all non performance-critical APIs
close #591
> Jinghan/refresh informer for all non performance-critical oomstore APIs

- featctl/cmd/root.go
- oomd/root.go
Let `featctl` and `oomd` share the same config.
> refactor: unify config paths

- internal/database/offline/mock_offline/store.go
- internal/database/offline/postgres/export.go
- internal/database/offline/store.go
- internal/database/offline/test_impl/export.go
- internal/database/offline/test_impl/import.go
- internal/database/online/postgres/import.go
- internal/database/online/redis/import.go
- internal/database/online/test_impl/util.go
- internal/database/online/types.go
- oomctl/cmd/export_helper.go
- pkg/oomstore/export.go
- pkg/oomstore/export_test.go
- pkg/oomstore/sync.go
- pkg/oomstore/sync_test.go
- pkg/oomstore/types/types.go
This PR does:
- for offline method `Export`: separate record and error to two channels
- for online method `Import`: takes in error channel from export as an argument
- for oomstore API `Export`: wrap return results to struct `ExportResult`
- for oomstore API `Sync`: pass down export error channel
- for featctl cmd `export`: modify print out functions
> Jinghan/refactor return type of API Export

- pkg/oomstore/export.go
- pkg/oomstore/join.go
- pkg/oomstore/types/options.go
This PR adds a new oomstore API `ExportByFile`, which exports feature values to a user-specified output file path.
related to #598
> Jinghan/implement oomstore API ExportByFile

- sdk/python/src/oomstore/client.py
This PR implements python sdk `export` and `channel_export`.
related to #598
> feat(sdk/python): implement python sdk export and channel_export

- internal/database/offline/postgres/helper.go
- internal/database/offline/postgres/join.go
- internal/database/offline/test_impl/join.go
- internal/database/offline/types.go
- pkg/oomstore/join.go
- pkg/oomstore/types/options.go
- pkg/oomstore/types/types.go
This PR refactors oomstore API `ChannelJoin`:
- add field `Values` to `types.EntityRow`
- refactor offline db method `Join`
TODO:
- refactor oomstore API `Join`
- refactor oomcli command `join`
related to #533
> Jinghan/add field `Values` to API ChannelJoin

- internal/database/metadata/informer/informer.go
- internal/database/metadata/informer/informer_test.go
- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/postgres/entity_test.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/entity.go
- oomcli/cmd/list_entity.go
- pkg/oomstore/apply.go
- pkg/oomstore/entity.go
- pkg/oomstore/feature.go
- pkg/oomstore/group.go
This PR does: 
- replace `CacheGetEntity`, `CacheGetEntityByName`, `CacheListEntity` by db-based methods
- delete entity's informer-based methods
related to #661
> Jinghan/use db-based methods for GetEntity(ByName) and ListEntity

- internal/database/metadata/informer/informer.go
- internal/database/metadata/informer/informer_test.go
- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/postgres/group.go
- internal/database/metadata/postgres/group_test.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/group.go
- internal/database/metadata/test_impl/revision.go
- oomcli/cmd/list_group.go
- pkg/oomstore/apply.go
- pkg/oomstore/export_test.go
- pkg/oomstore/feature.go
- pkg/oomstore/feature_test.go
- pkg/oomstore/group.go
- pkg/oomstore/import.go
- pkg/oomstore/import_test.go
- pkg/oomstore/sync_test.go
This PR does:
- replace `CacheGetGroup`, `CacheGetGroupByName`, `CacheListGroup` by db-based methods
- delete group's informer-based methods
related to #661
> Jinghan/use db-based methods for GetGroup(ByName) and ListGroup

- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/postgres/db.go
- internal/database/metadata/postgres/group.go
- internal/database/metadata/postgres/revision.go
- internal/database/metadata/postgres/revision_test.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/group.go
- internal/database/metadata/test_impl/revision.go
- pkg/oomstore/group.go
- pkg/oomstore/types/revision.go
This PR implements db-based revision methods: `GetRevision`, `GetRevisionBy`, `ListRevision`.
> Jinghan/implement db-based revision methods

- internal/database/metadata/informer/informer.go
- internal/database/metadata/informer/informer_test.go
- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/postgres/feature_test.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/feature.go
- oomcli/test/test_join.sh
- pkg/oomstore/apply.go
- pkg/oomstore/apply_test.go
- pkg/oomstore/export_test.go
- pkg/oomstore/feature.go
- pkg/oomstore/import.go
- pkg/oomstore/import_test.go
- pkg/oomstore/join.go
- pkg/oomstore/join_test.go
- pkg/oomstore/sync_test.go
This PR replaces informer-based feature methods by db-based, except `CacheListFeature`, which is used in online_query.
close #661
> Jinghan/replace informer-based feature methods

- pkg/oomstore/apply.go
- pkg/oomstore/types/apply/apply.go
Previously, metastore did not support the GetXXX family of functions at the transaction level, making the apply implementation cumbersome. With the merging of  #697  into the main branch, metadata is now supported. So here is a simplified implementation of apply
> refactor(oomstore/apply): simplify the implementation of apply using transaction Get methods

- oomcli/cmd/get_meta.go
- oomcli/cmd/get_meta_feature.go
- oomcli/cmd/util.go
This PR adds a new output format `Column`, which will be used as default format for sub command `get meta`.
> Jinghan/add output format `Column` for sub command `get meta`

- oomcli/cmd/get_meta_entity.go
- oomcli/cmd/get_meta_feature.go
- oomcli/cmd/get_meta_group.go
- oomcli/test/test_apply_entity.sh
- oomcli/test/test_apply_feature.sh
- oomcli/test/test_apply_group.sh
- oomcli/test/test_get_meta_feature.sh
- oomcli/test/test_update_feature.sh
This PR does:
- support output format `Column` for `get meta entity` and `get meta group`
- add `ID` and `DESCRIPTION` for command `get meta feature`
```
oomcli get meta entity --wide
ID  NAME  LENGTH  DESCRIPTION  CREATE-TIME           MODIFY-TIME
1   user  8       user ID      2021-11-18T08:05:37Z  2021-11-18T08:05:37Z
oomcli get meta group --wide
ID  NAME               ENTITY  DESCRIPTION                  ONLINE-REVISION-ID  CREATE-TIME           MODIFY-TIME
1   account            user    user account info            3                   2021-11-16T07:35:15Z  2021-11-17T03:56:37Z
2   transaction_stats  user    user transaction statistics  4                   2021-11-16T07:35:18Z  2021-11-17T04:02:12Z
```
> Jinghan/support `Column` output format for get meta commands

- oomcli/cmd/get_meta.go
- oomcli/cmd/get_meta_feature.go
- oomcli/cmd/util.go
- oomcli/test/test_get_meta_feature.sh
- pkg/oomstore/types/apply/apply.go
this PR is added `-o yaml` option for subcommand `get meta feature`. 
one feature:
```yaml
(base) ➜  oomcli git:(feat/feature_output_in_yaml) ✗ oomcli get meta feature state -o yaml
kind: Feature
name: state
group-name: account
db-value-type: varchar(32)
description: varchar(32)
(base) ➜  oomcli git:(feat/feature_output_in_yaml) ✗ 
```
multiple features:
```yaml
(base) ➜  oomcli git:(feat/feature_output_in_yaml) ✗ ./oomcli get meta feature -o yaml      
items:
- kind: Feature
name: state
group-name: account
db-value-type: varchar(32)
description: varchar(32)
- kind: Feature
name: credit_score
group-name: account
db-value-type: int
description: int
- kind: Feature
name: account_age_days
group-name: account
db-value-type: int
description: int
(base) ➜  oomcli …
```
> feat(oomctl): subcommand get meta feature add -o yaml option

- oomcli/cmd/get_meta_group.go
- oomcli/test/test_get_meta_feature.sh
- oomcli/test/test_get_meta_group.sh
- oomcli/test/util.sh
- pkg/oomstore/types/apply/apply.go
- pkg/oomstore/types/group.go
this PR is added -o yaml option for subcommand `get meta group`.
one group:
```yaml
(base) ➜  oomcli git:(feat/group_output_in_yaml) ✗ oomcli get meta group account -o yaml
kind: Group
name: account
entity-name: user
category: batch
description: user account info
features:
- name: credit_score
db-value-type: int
description: ""
- name: account_age_days
db-value-type: int
description: ""
- name: has_2fa_installed
db-value-type: bool
description: ""
- name: state
db-value-type: varchar(32)
description: description
```
multiple groups:
```yaml
(base) ➜  oomcli git:(feat/group_output_in_yaml) ✗ oomcli get meta group -o yaml        
items:
- kind: Group
name: account
entity-name: user
category: batch
description: user account info
features:
- name: credit_score
db-value-type: int
description: …
```
> feat/subcommand get meta group add -o yaml option

- internal/database/dbutil/db_opt.go
- internal/database/dbutil/sql.go
- internal/database/offline/bigquery/join.go
- internal/database/offline/bigquery/join_helper.go
- internal/database/offline/sqlutil/join.go
- internal/database/offline/sqlutil/join_helper.go
This PR does:
- define `dbutil.DBOpt`, add method `ExecContext` and `BuildInsertQuery`
- add helper function `PrepareEntityRowsTable`
- reuse `PrepareEntityRowsTable` in `sqlutil.Join` and `bigquery.Join`.
related to #780
> Jinghan/add helper PrepareEntityRowsTable for method `Join`

- internal/database/dbutil/db_opt.go
- internal/database/dbutil/type_mapping.go
- internal/database/offline/bigquery/join.go
- internal/database/offline/bigquery/join_helper.go
- internal/database/offline/sqlutil/join.go
- internal/database/offline/sqlutil/join_helper.go
This PR unifies helper function `JoinOneGroup`, now it could be used by `bigquery.Join` and `sqlutil.Join`.
related to #780
> Improve Join: unify helper func `JoinOneGroup`

- internal/database/offline/bigquery/join.go
- internal/database/offline/bigquery/join_helper.go
- internal/database/offline/sqlutil/join.go
- internal/database/offline/sqlutil/join_helper.go
This PR unifies helper function `ReadJoinedTable`, now it is used in both `bigquery.Join` and `sqlutil.Join`.
related to #780
> Improve Join: unify helper func ReadJoinedTable

- internal/database/metadata/mysql/group.go
- internal/database/metadata/postgres/group.go
- internal/database/metadata/sqlite/group.go
- internal/database/metadata/test_impl/feature.go
- internal/database/metadata/test_impl/group.go
- internal/database/metadata/test_impl/revision.go
- internal/database/metadata/types.go
- oomcli/cmd/types.go
- oomcli/test/test_apply_entity.sh
- pkg/oomstore/apply.go
- pkg/oomstore/feature.go
- pkg/oomstore/feature_test.go
- pkg/oomstore/group.go
- pkg/oomstore/join.go
- pkg/oomstore/online_query_test.go
- pkg/oomstore/types/apply/apply.go
- pkg/oomstore/types/group.go
- pkg/oomstore/types/types.go
since the group also have two kinds (Batch or Stream), so this PR does:
1. rename `FeatureBatchCategory` and `FeatureStreamCategory` to `BatchCategory` and `StreamCategory`
2. define enum type `types.Category`
relate #820
> refactor(tyeps): rename FeatureXXXCategory to Category

- internal/database/metadata/informer/feature.go
- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/sqlutil/feature.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/feature.go
- internal/database/metadata/types.go
- oomcli/cmd/edit_feature.go
- oomcli/cmd/get_meta_feature.go
- oomcli/cmd/update_feature.go
- oomcli/test/test_get_meta_feature.sh
- pkg/oomstore/export.go
- pkg/oomstore/feature.go
- pkg/oomstore/join.go
- pkg/oomstore/join_test.go
- pkg/oomstore/online_query.go
- pkg/oomstore/online_query_test.go
- pkg/oomstore/types/feature.go
- pkg/oomstore/types/options.go
This PR does:
- use `FeatureFullName` instead of `FeatureName` in metadata store
- refactor feature related APIs (`GetFeatureByName`, `ListFeature`, `UpdateFeature`)
close #810
> Jinghan/Replace `FeatureName` by `FeatureFullName` for feature APIs

- internal/database/offline/bigquery/join.go
- internal/database/offline/sqlutil/join.go
- internal/database/offline/test_impl/join.go
- oomagent/server.go
- oomcli/cmd/join_helper.go
- oomcli/test/test_join.sh
- pkg/oomstore/join.go
- pkg/oomstore/join_test.go
- pkg/oomstore/types/options.go
This PR refactors API `Join`: use `FeatureFullName` instead of `FeatureName`.
related to #811 
TODO:
> Jinghan/use `FeatureFullName` for API Join

- internal/database/online/cassandra/get.go
- internal/database/online/dynamodb/get.go
- internal/database/online/redis/get.go
- internal/database/online/sqlutil/get.go
- internal/database/online/test_impl/get.go
- internal/database/online/test_impl/purge.go
- internal/database/online/test_impl/util.go
- oomagent/server.go
- oomcli/cmd/get_online.go
- oomcli/cmd/register_group.go
- oomcli/test/test_online_get.sh
- oomcli/test/test_update_feature.sh
- oomcli/test/util.sh
- pkg/oomstore/online_query.go
- pkg/oomstore/online_query_test.go
- pkg/oomstore/types/feature_values.go
- pkg/oomstore/types/options.go
This PR does:
- use `FullName` for API `OnlineGet` and `MultiOnlineGet`
- add `category` for command `register group`
close #811
> Jinghan/use `FullName` for API `OnlineGet`

- internal/database/metadata/sqlutil/feature.go
- internal/database/metadata/sqlutil/group.go
- internal/database/metadata/sqlutil/revision.go
- oomagent/test/test_channel_import.sh
- oomagent/test/test_channel_join.sh
- oomagent/test/test_import_from_file.sh
- oomagent/test/test_join_using_file.sh
- oomagent/test/test_online_get.sh
- oomagent/test/test_online_multi_get.sh
This PR refactors all `List` methods (except `CacheListFeature`): order output objects by id.
close #830
> `List` method: order by id

- internal/database/metadata/types.go
- internal/database/offline/test_impl/join.go
- internal/database/offline/types.go
- internal/database/online/cassandra/store_test.go
- pkg/oomstore/join.go
- pkg/oomstore/online_query_test.go
This PR does:
- modify API `Join`: pass down CdcTable for streaming features
- move `RevisionRange` from package metadata to package offline
- skip cassandra unit tests until we separate snapshot schema and cdc schema
close #803 
TODO:
> Jinghan/Modify API `Join`

- internal/database/metadata/sqlutil/revision.go
- internal/database/metadata/test_impl/revision.go
- internal/database/metadata/types.go
This PR modifies metadata method `UpdateRevision`: able to update `snapshot_table`.
This feature will be used for creating snapshot tables for streaming features.
related to #805
> Jinghan/update revision's  `snapshot_table`

- internal/database/offline/bigquery/join.go
- internal/database/offline/sqlutil/join.go
- internal/database/offline/sqlutil/join_helper.go
This PR improves offline method `Join`: 
- previously, we add quotes for `entity_key` and `unix_milli` outside of the query
- now, we move the quote behavior inside the query
> Improve Join: quote entity_key and unix_milli inside query

- oomcli/cmd/snapshot.go
This PR adds a command `snapshot` for oomcli.
related to #805 
TODO:
> feat(oomcli/cmd): add command `snapshot` for oomcli

- internal/database/database.go
- pkg/oomstore/types/config.go
It is so easy to forget. Let's come up with a way to prevent this. Running sanity integration test is one way.
> fix: add missing backend to switch

- oomcli/test/test_export.sh
Because different offline databases output results in different orders, this PR modifies `export` integration test to make it compatible with different offline stores.
related to #894
> test(oomcli/test): modify export integration test

- internal/database/offline/types.go
- pkg/oomstore/export.go
- pkg/oomstore/types/options.go
- pkg/oomstore/types/revision.go
This PR adds a new API `ChannelExportStream`, which exports stream feature values given a timestamp.
TODO:
related to #802
> Jinghan/implement API `ChannelExportStream`

- internal/database/offline/bigquery/export.go
- internal/database/offline/bigquery/store_test.go
- internal/database/offline/sqlutil/export.go
- internal/database/offline/sqlutil/export_helper.go
This PR does:
- modify `sqlutil.Export`, to make it adapt with bigquery offline store
- use `sqlutil.Export` for bigquery method `Export`
related to #802
> Jinghan/refactor `sqlutil.Export`: adapt with bigquery store

- oomagent/codegen/oomagent.pb.go
- oomagent/codegen/oomagent_grpc.pb.go
- oomagent/server.go
- oomcli/cmd/export.go
- oomcli/cmd/export_helper.go
- pkg/oomstore/export.go
- pkg/oomstore/export_test.go
- pkg/oomstore/types/options.go
This PR renames API `Export` to `ExportBatch`. In later PRs, we will implement a new `Export` API, which can export both batch and streaming features.
related to #802
> refactor: rename Export to ExportBatch

- internal/database/offline/bigquery/export.go
- internal/database/offline/bigquery/store_test.go
- internal/database/offline/mock_offline/store.go
- internal/database/offline/mysql/store.go
- internal/database/offline/postgres/store.go
- internal/database/offline/redshift/store.go
- internal/database/offline/snowflake/store.go
- internal/database/offline/sqlite/store.go
- internal/database/offline/sqlutil/export.go
- internal/database/offline/sqlutil/export_helper.go
- internal/database/offline/sqlutil/join_helper.go
- internal/database/offline/store.go
- internal/database/offline/test_impl/export.go
- internal/database/offline/test_impl/import.go
- internal/database/offline/test_impl/snapshot.go
- internal/database/offline/types.go
- pkg/oomstore/export.go
- pkg/oomstore/export_test.go
- pkg/oomstore/sync.go
- pkg/oomstore/sync_test.go
This PR re-implements offline method `Export`, which supports exporting multi-group, multi-type (batch / streaming) features.
related to #962 
TODO
> Jinghan/implement offline method `Export`

- internal/database/offline/bigquery/export.go
- internal/database/offline/mock_offline/store.go
- internal/database/offline/mysql/store.go
- internal/database/offline/postgres/store.go
- internal/database/offline/redshift/store.go
- internal/database/offline/snowflake/store.go
- internal/database/offline/sqlite/store.go
- internal/database/offline/sqlutil/export.go
- internal/database/offline/store.go
- internal/database/offline/test_impl/export.go
- pkg/oomstore/export.go
This PR changes the return type of offline method `Export` to 
```
Export(ctx context.Context, opt ExportOpt) (*types.ExportResult, error)
type ExportResult struct {
Header []string
Data   <-chan ExportRecord
error  <-chan error
}
```
So that we generate `Header` and `Data` in the same place.
related to #962
> Jinghan/refactor Export return type

- internal/database/offline/sqlutil/snapshot.go
- internal/database/offline/test_impl/join.go
- internal/database/offline/test_impl/snapshot.go
- pkg/oomstore/revision.go
This PR adds `unix_milli` column to streaming feature's snapshot table.
TODO:
related to #994
> Jinghan/Add `unix_milli` column to snapshot table

- pkg/oomstore/cache.go
- pkg/oomstore/oomstore.go
- pkg/oomstore/types/config.go
resolve: #980 
example:
```yaml
online-store:
postgres:
host: 127.0.0.1
port: 25432
user: postgres
password: postgres
database: oomstore
offline-store:
postgres:
host: 127.0.0.1
port: 25432
user: postgres
password: postgres
database: oomstore
metadata-store:
postgres:
host: 127.0.0.1
port: 25432
user: postgres
password: postgres
database: oomstore
stream-push-processor:
revision-interval: 24h
period: 5m
min-period: 2m
buffer-interval: 1000
```
> feat(oomsotre/stream-cache): make stream push processor configurable

- internal/database/dbutil/schema.go
- internal/database/offline/bigquery/store.go
- internal/database/offline/bigquery/store_test.go
- internal/database/offline/mysql/store_test.go
- internal/database/offline/postgres/store_test.go
- internal/database/offline/redshift/store.go
- internal/database/offline/redshift/store_test.go
- internal/database/offline/snowflake/store_test.go
- internal/database/offline/sqlite/store_test.go
- internal/database/offline/sqlutil/create_table.go
- internal/database/offline/test_impl/create_table.go
- internal/database/offline/test_impl/export.go
- internal/database/offline/test_impl/push.go
- internal/database/offline/types.go
- pkg/oomstore/cache.go
- pkg/oomstore/revision.go
- pkg/oomstore/types/types.go
This PR refactors offline method `CreateTable`: replace `IsCDC` by `TableType`, so that we could differentiate different table types clearly.
related to #994
> Jinghan/modify offline method `CreateTable`

- internal/database/dbutil/data_loader.go
- internal/database/offline/postgres/util.go
- internal/database/offline/sqlutil/import.go
- pkg/oomstore/import.go
This PR refactors helper functions `loadDataFromSource` and `ReadLine`, make them able to handle `unix_milli` when parsing data from source.
This refactor will be used in later PRs to load data for streaming features.
> Jinghan/refactor helper `loadDataFromSource`

- internal/database/dbutil/data_loader.go
- internal/database/offline/postgres/util.go
This PR simplifies the helper function `ReadLine`: remove parameter `backend`.
> refactor(database): remove backend from ReadLine

- go.mod
- internal/database/metadata/informer/feature.go
- internal/database/metadata/informer/informer.go
- internal/database/metadata/informer/informer_test.go
- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/feature.go
- internal/database/metadata/types.go
- pkg/oomstore/online_query.go
- pkg/oomstore/online_query_test.go
- pkg/oomstore/push.go
This PR refactors informer method `ListCachedFeature`: add parameter `groupName` and `groupID` so that callers could filter features by group.
related to #1008
> Jinghan/filter features by group in `ListCachedFeature`

- pkg/errdefs/errdefs.go
resolve #1082 
relate [stack overflow](https://stackoverflow.com/questions/70851429/golang-pkg-errors-how-to-print-custom-wrapped-errors)
> fix(oomstore/errdefs): fix wrapped error does not print out the call stack

- internal/database/dbutil/sql.go
- internal/database/online/cassandra/store.go
- internal/database/online/dynamodb/import.go
- internal/database/online/dynamodb/store.go
- internal/database/online/dynamodb/stream.go
- internal/database/online/mock_online/store.go
- internal/database/online/mysql/store.go
- internal/database/online/mysql/store_test.go
- internal/database/online/postgres/store.go
- internal/database/online/postgres/store_test.go
- internal/database/online/redis/store.go
- internal/database/online/sqlite/store.go
- internal/database/online/sqlite/store_test.go
- internal/database/online/sqlutil/create_table.go
- internal/database/online/store.go
- internal/database/online/test_impl/create_table.go
- internal/database/online/tikv/store.go
- internal/database/online/types.go
This PR adds a new online method `CreateTable`, which creates table for both batch and streaming feature groups.
This method will replace `PrepareStreamTable` in later PRs.
> Jinghan/implement online method `CreateTable`

- pkg/oomstore/apply.go
This PR fixes a bug in `apply`: if newly-created group conflicts with already-existing group in `entityName` or `category`, we should not allow the group to be changed.
resolve #1095
> refactor(pkg/oomstore): group's Entity and Category should not change

- README.md
- oomcli/cmd/get_online.go
So that it is consistent to `--feature`
> refactor: use entity-key to represent plural to be consistent

- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/mysql/db.go
- internal/database/metadata/mysql/revision.go
- internal/database/metadata/mysql/tx.go
- internal/database/metadata/postgres/db.go
- internal/database/metadata/postgres/revision.go
- internal/database/metadata/postgres/tx.go
- internal/database/metadata/sqlite/db.go
- internal/database/metadata/sqlite/revision.go
- internal/database/metadata/sqlite/tx.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/revision.go
- pkg/oomstore/import.go
- pkg/oomstore/import_stream.go
- pkg/oomstore/push_processor.go
- pkg/oomstore/revision.go
This PR refactors metadata method `CreateRevision`: not return `snapshotTableName`.
In the previous PR, method `CreateRevision` no longer create `snapshotTable`, it shouldn't return `snapshotTableName` any more.
> Jinghan/refactor metadata method `CreateRevision`

- pkg/oomstore/push.go
API `Push` can only be used by streaming features. This PR checks group category before pushing data to offline/online store.
> feat(pkg/oomstore): check group category in API Push

- pkg/oomstore/join.go
Before `Join`, streaming features should take snapshot.
> feat(pkg/oomstore): take snapshot before Join

- oomcli/cmd/sync.go
> refactor(oomcli/sync): the parameter revision-id set to not required

- pkg/oomstore/revision.go
- pkg/oomstore/snapshot.go
This PR deprecates the helper function `createFirstSnapshotTable` since we already have dummy revision (with dummy snapshot table).
> feat(pkg/oomstore): deprecate helper func `createFirstSnapshotTable`

- internal/database/metadata/mock_metadata/store.go
- internal/database/metadata/mysql/db.go
- internal/database/metadata/mysql/tx.go
- internal/database/metadata/postgres/db.go
- internal/database/metadata/postgres/tx.go
- internal/database/metadata/sqlite/db.go
- internal/database/metadata/sqlite/tx.go
- internal/database/metadata/sqlutil/feature.go
- internal/database/metadata/sqlutil/group.go
- internal/database/metadata/sqlutil/revision.go
- internal/database/metadata/store.go
- internal/database/metadata/test_impl/group.go
- internal/database/metadata/types.go
- pkg/oomstore/group.go
This PR modifies the metadata method `ListGroup`: add argument `ListGroupOpt`, so that `ListGroup` could be used in more situations.
> Jinghan/add `ListGroupOpt` to metadata method `ListGroup`

- internal/database/offline/sqlutil/create_table.go
- internal/database/offline/sqlutil/snapshot.go
This PR refactors offline method `Snapshot`: reuse method `CreateTable` to simplify the logic.
> Jinghan/reuse offline method `CreateTable` in `Snapshot` method

- oomagent/root.go
- oomcli/cmd/root.go
the package `io/ioutil` will be deprecated, see: https://github.com/go-critic/go-critic/issues/1019
> refactor(oomagent|oomcli): replace ioutil.ReadFile with os.ReadFile
