oom-ai/oomstore

.github/workflows/release.yml, featctl/.gitignore, featctl/.goreleaser.yml, featctl/Makefile
This pr replace `action-automatic-releases` with [goreleaser](https://github.com/goreleaser/goreleaser) which works better for golang projects.
=> improve binary release

featctl/test/test_describe_entity.sh, featctl/test/test_describe_feature.sh, featctl/test/test_describe_group.sh, featctl/test/test_list_entity.sh, featctl/test/test_list_feature.sh, featctl/test/test_list_group.sh, featctl/test/util.sh
Make outdated integration tests work
=> test: fix integration tests

internal/database/online/postgres/import.go
This PR avoids renaming online `data_table` when syncing feature values from offline store to online store.
=> Jinghan/refactor online.Import

.codecov.yml
This pr relaxes the fail threshold of codecov
=> ci: udpate codecov config

.github/workflows/release.yml, featctl/.goreleaser.yml
=> ci: fix ci release

internal/database/offline/postgres/join.go
This PR fixes offline store method `Join`: drop temporary tables after row read complete.
=> refactor(database/offline): drop tables after row read complete

featctl/cmd/export.go, featctl/cmd/export_helper.go, pkg/oomstore/export.go, pkg/oomstore/export_test.go, pkg/oomstore/types/options.go
close https://github.com/oom-ai/oomstore/issues/527
=> chore: shorter public API name

featctl/cmd/apply.go, featctl/cmd/apply.md, go.mod, go.sum, pkg/oomstore/apply.go, pkg/oomstore/apply_test.go, pkg/oomstore/types/apply/apply.go, pkg/oomstore/types/options.go
=> [wip] app apply

featctl/cmd/apply.md, pkg/oomstore/apply_test.go, pkg/oomstore/types/apply/apply.go
This PR unifies `DbValueType` to `db-value-type` in apply.yaml.
=> Jinghan/unify to `db-value-type` in apply yaml

featctl/test/test_apply_entity.sh
this PR is add integration test of apply entity
=> test(featctl): add integration test of apply entity

featctl/test/test_apply_group.sh
this PR is add integration-test of apply group
=> test: add integration-test of apply group

featctl/test/test_apply_feature.sh
this PR is add integration-test of apply feature
=> test: add integration-test of apply feature

oomd/server.go
=> feat: add oomd server template

oomd/server.go
This PR implements grpc API `OnlineGet`.
TODO:
- add helpers to generate response and error
related to #556
=> feat(oomd): implement grpc API OnlineGet

featctl/cmd/apply.md, featctl/test/test_apply_entity.sh, pkg/oomstore/apply.go, pkg/oomstore/apply_test.go
this PR adds unit-test for oomstore/apply
=> Unit test/oomstore apply

oomd/server.go
This PR implements grpc API Sync.
relate #556
=> feat(oomd): implement sync

oomd/server.go
This PR implements grpc API `OnlineMultiGet`.
related to #556
=> Jinghan/implement grpc API OnlineMultiGet

oomd/server.go, oomd/test/client.go
To test your change locally,
1. In one session, `go run oomd/server.go`
2. In another session, `go run oomd/test/client.go`
=> test: run grpc locally

oomd/server.go
=> refactor: fix lint

go.mod, go.sum
=> chore: bump up dependencies

.github/wip.yml
Configure wip bot also checking keyword in label.
=> ci: configure wip bot

oomd/server.go
This PR implements grpc API `JoinByFile`.
related to #556
=> feat(oomd/server): implement grpc API JoinByFile

oomd/server.go, oomd/test/client.go
this PR is implemented grpc API import
relate #556
=> feat(oomd): implement grpc import api

Makefile
The issue dates back to https://github.com/protocolbuffers/protobuf/issues/1491
=> fix: edit generated python code st relative import works

featctl/cmd/import.go, go.mod, pkg/oomstore/import.go, pkg/oomstore/types/options.go
This PR implements oomstore API `ImportByFile`.
=> Jinghan/implement oomstore API ImportByFile

featctl/cmd/root.go, go.mod, oomd/root.go
=> chore: replace yaml.v2 with yaml.v3

featctl/cmd/apply.md, featctl/test/test_apply_entity.sh, featctl/test/test_apply_feature.sh, featctl/test/test_apply_group.sh, pkg/oomstore/apply.go, pkg/oomstore/apply_test.go
this PR is changing resource object kind field from all lower case to first letter upper case as k8s
=> refactor(oomstore/apply): change kind filed from all lower case to first letter upper case

sdk/python/client.py
relate https://github.com/oom-ai/oomstore/issues/582
=> feat: implement python sdk api needed for quickstart

sdk/python/client.py
Start oomd asynchronously at initialisation
=> feat(sdk/python): start oomd asynchronously at initialisation

sdk/python/client.py
the localhost and 127.0.0.1 sometimes have different behavior.  look that: https://stackoverflow.com/questions/7382602/what-is-the-difference-between-127-0-0-1-and-localhost
=> refactor(sdk/python): replace localhost with 127.0.0.1

oomd/test/test_online_get.sh, oomd/test/test_online_multi_get.sh
=> test: add grpc online-multi-get test

Makefile, oomd/test/test_online_get.sh, oomd/test/test_online_multi_get.sh, oomd/test/test_sync.sh, oomd/test/util.sh
=> refactor grpc tests

.gitignore, oomd/test/test_import.sh, oomd/test/util.sh, pkg/oomstore/import.go
=> test: add grpc import test

oomd/test/test_import_from_file.sh
=> test: add grpc import-from-file test

oomd/server.go
This PR implements rpc methods `Export` and `ChannelExport`.
related to #598
=> feat(oomd/server): implement rpc Export and ChannelExport

oomd/test/util.sh
=> test: fix darwin compability

oomd/server.go
The code is written by @jinghancc , I simply copy and paste
=> feat: implement ChannelJoin rpc

.github/workflows/release.yml, .gitignore, .goreleaser.yml
=> ci: publish oomd on release page

oomcli/cmd/join_helper.go, oomcli/test/test_join.sh, pkg/oomstore/join.go
This PR does:
- refactor oomstore API `Join`: add header to input file, add other real-time feature values to input file
- refactor oomcli command `join`: same as the above
close #533
=> Jinghan/refactor API and command Join

internal/database/metadata/mock_metadata/store.go, internal/database/metadata/postgres/db.go, internal/database/metadata/postgres/group.go, internal/database/metadata/postgres/group_test.go, internal/database/metadata/store.go, internal/database/metadata/test_impl/group.go
This PR implementS metadata db-based methods `GetGroup` and `GetGroupByName`.
=> Jinghan/implement metadata db-based methods GetGroup and GetGroupByName

internal/database/metadata/mock_metadata/store.go, internal/database/metadata/postgres/db.go, internal/database/metadata/postgres/group.go, internal/database/metadata/postgres/group_test.go, internal/database/metadata/store.go, internal/database/metadata/test_impl/group.go, pkg/oomstore/types/group.go
This PR implements db-based method `ListGroup`.
=> Jinghan/implement db-based method ListGroup

internal/database/metadata/mock_metadata/store.go, internal/database/metadata/postgres/db.go, internal/database/metadata/postgres/feature.go, internal/database/metadata/postgres/feature_test.go, internal/database/metadata/postgres/tx.go, internal/database/metadata/store.go, internal/database/metadata/test_impl/feature.go
This PR implements db-based method GetFeature.
=> Implement get feature methods

internal/database/metadata/mock_metadata/store.go, internal/database/metadata/postgres/db.go, internal/database/metadata/postgres/feature.go, internal/database/metadata/postgres/feature_test.go, internal/database/metadata/postgres/tx.go, internal/database/metadata/store.go, internal/database/metadata/test_impl/feature.go
This PR implements db-based method GetFeatureByName.
=> Implement GetFeatureByName

oomagent/server.go
=> feat: only send header in the very first ChannelJoinResponse

Makefile, oomcli/test/start_playground.sh
Add three playground related targets in makefile:
```sh
make start_playground
make stop_playground
make restart_playground
```
=> chore: add playground in makefile

oomagent/test/test_export_to_file.sh
=> test: add grpc export (to file) test

oomagent/test/test_channel_export.sh
=> test: add grpc export (using channel) test

oomcli/cmd/get_meta.go, oomcli/cmd/get_meta_feature.go, oomcli/test/test_apply_entity.sh, oomcli/test/test_apply_feature.sh, oomcli/test/test_apply_group.sh, oomcli/test/test_get_meta_feature.sh, oomcli/test/test_update_feature.sh
This PR adds option `--wide` for oomcli command `get meta feature`.
related to #714
=> Jinghan/add option wide for command `get meta feature`

oomcli/cmd/get_meta_entity.go, oomcli/test/test_apply_entity.sh, oomcli/test/test_get_meta_entity.sh, oomcli/test/test_update_entity.sh
This PR addS option --wide to oomcli command `get meta entity`.
related to #714
=> Jinghan/add option --wide to oomcli command `get meta entity`

internal/database/metadata/mock_metadata/store.go, internal/database/metadata/postgres/database.go, internal/database/metadata/postgres/database_test.go, internal/database/metadata/store.go, internal/database/metadata/test_impl/ping.go, internal/database/offline/mock_offline/store.go, internal/database/offline/postgres/database.go, internal/database/offline/postgres/ping_test.go, internal/database/offline/store.go, internal/database/offline/test_impl/ping.go, internal/database/online/mock_online/store.go, internal/database/online/postgres/database.go, internal/database/online/postgres/database_test.go, internal/database/online/redis/database.go, internal/database/online/redis/database_test.go, internal/database/online/store.go, internal/database/online/test_impl/ping.go, oomagent/server.go, pkg/oomstore/oomstore.go, pkg/oomstore/ping_test.go
=> feature: add health check api for oomstore

oomcli/cmd/get_meta_group.go, oomcli/test/test_apply_entity.sh, oomcli/test/test_apply_group.sh, oomcli/test/test_get_meta_group.sh
This PR adds option `--wide` to oomcli command `get meta group`.
close #714
=> Jinghan/add option wide to command `get meta group`

go.mod, internal/database/metadata/mysql/database.go, internal/database/metadata/mysql/database_test.go, internal/database/metadata/mysql/db.go, internal/database/metadata/mysql/db_test.go, internal/database/metadata/mysql/entity.go, internal/database/metadata/postgres/create_database.go, internal/database/metadata/postgres/database.go, internal/database/metadata/postgres/database_test.go, internal/database/metadata/postgres/db.go, internal/database/metadata/postgres/entity.go, internal/database/metadata/postgres/group.go, internal/database/metadata/postgres/tx.go, internal/database/metadata/sqlutil/db.go, internal/database/metadata/sqlutil/entity.go
This PR implements mysql methods for `entity`.
Previous PR: #730 
TODO:
- implement mysql methods for other tables
related to #718
=> Jinghan/add mysql methods for `entity`

internal/database/metadata/mysql/db.go, internal/database/metadata/mysql/db_test.go, internal/database/metadata/mysql/group.go, internal/database/metadata/sqlutil/group.go
This PR implements mysql methods for table `group`.
related to #718
=> Jinghan/implement mysql methods for `group`

internal/database/metadata/mysql/db.go, internal/database/metadata/mysql/db_test.go, internal/database/metadata/mysql/entity.go, internal/database/metadata/mysql/feature.go, internal/database/metadata/mysql/group.go, internal/database/metadata/postgres/db.go, internal/database/metadata/postgres/feature.go, internal/database/metadata/postgres/feature_test.go, internal/database/metadata/postgres/group.go, internal/database/metadata/postgres/revision.go, internal/database/metadata/postgres/tx.go, internal/database/metadata/sqlutil/feature.go, internal/database/metadata/test_impl/feature.go
This PR implements mysql methods for table `feature`.
related to #718
=> Jinghan/implement mysql methods for `feature`

internal/database/metadata/mysql/database.go, internal/database/metadata/mysql/db.go, internal/database/metadata/mysql/db_test.go, internal/database/metadata/mysql/revision.go, internal/database/metadata/mysql/tx.go, internal/database/metadata/postgres/db.go, internal/database/metadata/postgres/revision.go, internal/database/metadata/postgres/tx.go, internal/database/metadata/sqlutil/revision.go
This PR implements mysql methods for table `revision`.
related to #718
=> Jinghan/implement mysql methods for `revision`

internal/database/dbutil/type_mapping.go
close https://github.com/oom-ai/oomstore/issues/782
=> fix: redshift data type

internal/database/dbutil/db_opt.go
This PR simplifies dbOpt method `BuildInsertQuery`, since we can deal with placeholder issue in `dbOpt.ExecContext`.
related to #780
=> refactor(database): simplify dbOpt.BuildInsertQuery

internal/database/metadata/mysql/feature.go, internal/database/metadata/mysql/schema.go, internal/database/metadata/postgres/feature.go, internal/database/metadata/postgres/schema.go, internal/database/metadata/sqlite/feature.go, internal/database/metadata/sqlite/schema.go, internal/database/metadata/types.go, pkg/oomstore/feature.go, pkg/oomstore/feature_test.go, pkg/oomstore/types/feature.go
This PR does:
- add field `full_name` to feature table
- modify API `CreateFeature`: add full_name
close #809
=> Jinghan/Add field `full_name` to feature table

internal/database/metadata/mysql/group.go, internal/database/metadata/postgres/group.go, internal/database/metadata/sqlite/group.go, oomcli/cmd/register_batch_feature.go, pkg/oomstore/feature.go, pkg/oomstore/feature_test.go, pkg/oomstore/group.go, pkg/oomstore/types/options.go
this PR is renamed `CreateBatchFeature` to `CreateFeature` and makes it support create stream feature.
relate #820
=> rename CreateBatchFeature with CreateFeature

README.md, oomagent/test/data/driver_stats.yaml, oomagent/test/data/fraud_detection.yaml, oomcli/cmd/register_feature.go, oomcli/cmd/register_group.go, oomcli/cmd/types.go, oomcli/test/test_apply_entity.sh, oomcli/test/test_apply_group.sh, oomcli/test/test_get_meta_entity.sh, oomcli/test/test_get_meta_group.sh, oomcli/test/test_update_group.sh, oomcli/test/util.sh, pkg/oomstore/apply.go, pkg/oomstore/apply_test.go, pkg/oomstore/types/apply/apply.go, pkg/oomstore/types/types.go, sdk/python/src/test/test_client.py
=> apply/get meta support stream group/feature

internal/database/online/cassandra/store.go, internal/database/online/dynamodb/store.go, internal/database/online/mock_online/store.go, internal/database/online/mysql/store.go, internal/database/online/postgres/store.go, internal/database/online/redis/store.go, internal/database/online/sqlite/store.go, internal/database/online/store.go, internal/database/online/types.go
=> feat(online): add method push

internal/database/dbutil/schema.go, internal/database/dbutil/schema_test.go, internal/database/metadata/types.go, internal/database/offline/bigquery/join.go, internal/database/offline/sqlutil/export.go, internal/database/offline/sqlutil/join.go, internal/database/offline/sqlutil/join_helper.go, internal/database/offline/sqlutil/serialize.go, internal/database/offline/test_impl/join.go, internal/database/offline/types.go
This PR refactors offline method `Join` to handle streaming features.
related to #803
=> Jinghan/modify offline method `Join`: handle streaming features

internal/database/online/cassandra/store_test.go, internal/database/online/cassandra/stream.go, internal/database/online/dynamodb/store_test.go, internal/database/online/dynamodb/stream.go, internal/database/online/mysql/store_test.go, internal/database/online/postgres/store_test.go, internal/database/online/redis/store_test.go, internal/database/online/sqlite/store_test.go, internal/database/online/sqlutil/util.go, internal/database/online/test_impl/stream.go
this PR is add unit-test `TestPrepareStreamTable`
=> test(oomstore): add unit test TestPrepareStreamTable

pkg/oomstore/snapshot.go
This PR implements API `Snapshot`.
related to #805 
TODO:
=> feat(pkg/oomstore): implement API Snapshot

internal/database/offline/bigquery/join.go, internal/database/offline/bigquery/store.go, internal/database/offline/mysql/store.go, internal/database/offline/postgres/store.go, internal/database/offline/redshift/store.go, internal/database/offline/snowflake/store.go, internal/database/offline/sqlite/store.go, internal/database/online/cassandra/import.go, internal/database/online/cassandra/store.go, internal/database/online/cassandra/stream.go, internal/database/online/dynamodb/store.go, internal/database/online/mysql/store.go, internal/database/online/postgres/store.go, internal/database/online/redis/store.go, internal/database/online/sqlite/store.go, internal/database/online/tikv/store.go
Define `Backend` once in each `store.go` and use it elsewhere.
=> refactor: DRY refactor on backend

internal/database/online/mysql/store.go, internal/database/online/postgres/store.go, internal/database/online/sqlite/store.go, internal/database/online/sqlite/store_test.go, internal/database/online/sqlutil/push.go
this PR does:
1. refactor sqlutil.BuildPushCondition: wrap return values to a struct
2. sqlite implements the push method
relate #801
=> feature: online sqlite implement method push

internal/database/online/tidb/store_test.go
this PR added unit test of push implement for online/tidb.
relate #801
=> test(online/tidb): add push unit-test

internal/database/dbutil/type_mapping.go, internal/database/offline/bigquery/store_test.go, internal/database/offline/mysql/store.go, internal/database/offline/mysql/store_test.go, internal/database/offline/postgres/store_test.go, internal/database/offline/redshift/store_test.go, internal/database/offline/snowflake/store.go, internal/database/offline/snowflake/store_test.go, internal/database/offline/sqlite/store.go, internal/database/offline/sqlite/store_test.go, internal/database/offline/test_impl/table_schema.go, internal/database/offline/tidb/store_test.go
This PR implements offline method `TableSchema` for all backends.
=> Offline: implement `TableSchema` method

internal/database/metadata/mysql/revision.go, internal/database/metadata/postgres/revision.go, internal/database/metadata/sqlite/revision.go, internal/database/metadata/types.go
This PR modifies `CreateRevision` method: add `CdcTable` option when creating a new revision.
=> feat(database/metadata): add CdcTable to CreateRevision

internal/database/offline/snowflake/store_test.go
This PR cleans up snowflake database after running TestTableSchema.
=> test(database/offline): clean up snowflake database

internal/database/online/cassandra/get.go, internal/database/online/cassandra/import.go, internal/database/online/dynamodb/get.go, internal/database/online/dynamodb/import.go, internal/database/online/redis/get.go, internal/database/online/redis/import.go, internal/database/online/redis/push.go, internal/database/online/sqlutil/get.go, internal/database/online/sqlutil/import.go, internal/database/online/sqlutil/push.go, internal/database/online/test_impl/get.go, internal/database/online/test_impl/purge.go, internal/database/online/test_impl/stream.go, internal/database/online/test_impl/util.go, internal/database/online/tikv/get.go, internal/database/online/tikv/import.go, internal/database/online/tikv/push.go, internal/database/online/types.go, pkg/oomstore/online_query.go, pkg/oomstore/sync.go, pkg/oomstore/sync_test.go
this PR does rename `FeatureList` with `Features`.
=> chore: rename FeatureList with Features

internal/database/online/dynamodb/store.go, internal/database/online/dynamodb/store_test.go, internal/database/online/dynamodb/stream.go
this PR does:
1. online/dynamodb implement `push` method
2. add unit-test for push
relate #801
=> feat(online/dynamodb): implement push method

internal/database/dbutil/schema.go, internal/database/dbutil/schema_test.go, internal/database/offline/bigquery/store.go, internal/database/offline/sqlutil/create_table.go, internal/database/offline/sqlutil/import.go, internal/database/offline/sqlutil/snapshot.go, internal/database/offline/test_impl/create_table.go, internal/database/offline/test_impl/util.go, internal/database/offline/types.go, internal/database/online/cassandra/import.go, internal/database/online/sqlutil/import.go
Template for table schema becomes very complicated when supporting optional primary key and index. So I rewrite it using normal functions.
=> feature: offline table index

internal/database/dbutil/data_loader.go, internal/database/offline/postgres/util.go, internal/database/offline/sqlutil/export.go, internal/database/offline/sqlutil/import.go, pkg/oomstore/import.go
This PR fixes integration tests for backends combination `MySQL, MySQL, MySQL`:
- import: serialize import feature value (for boolean feature value, convert from string to int)
- export: deserialize export data (for boolean value type, convert from `int` to `bool`)
related to #894
=> Jinghan/fix integration test for MySQL backend

scripts/playgrounds.yaml
https://github.com/oom-ai/oomplay/pull/22
oomplay v6.0.0 supports sqilte.
=> test: update sqlite config

test_all.sh
This PR adds a script to run all backend  combinations.
related to #894
=> feat: add script to run all backend combinations

internal/database/dbutil/database.go, internal/database/dbutil/sql.go, internal/database/metadata/mysql/entity.go, internal/database/metadata/mysql/feature.go, internal/database/metadata/mysql/group.go, internal/database/metadata/mysql/revision.go, internal/database/metadata/mysql/store.go, internal/database/metadata/postgres/create_database.go, internal/database/metadata/postgres/entity.go, internal/database/metadata/postgres/feature.go, internal/database/metadata/postgres/group.go, internal/database/metadata/postgres/revision.go, internal/database/metadata/postgres/store.go, internal/database/metadata/sqlite/create_database.go, internal/database/metadata/sqlite/entity.go, internal/database/metadata/sqlite/feature.go, internal/database/metadata/sqlite/group.go, internal/database/metadata/sqlite/revision.go, internal/database/metadata/sqlite/store.go, internal/database/metadata/sqlutil/db.go, internal/database/metadata/sqlutil/entity.go, internal/database/metadata/sqlutil/feature.go, internal/database/metadata/sqlutil/group.go, internal/database/metadata/sqlutil/revision.go, internal/database/metadata/test_impl/entity.go, internal/database/metadata/test_impl/feature.go, internal/database/metadata/test_impl/group.go, pkg/oomstore/types/value_type.go
=> feat(metadata): error add stack trace

internal/database/offline/sqlutil/push.go, internal/database/offline/test_impl/push.go, internal/database/offline/types.go, pkg/oomstore/types/feature_values.go
=> fix(offline/push): add missing entity key and unix_milli

pkg/oomstore/push.go, pkg/oomstore/types/options.go
This PR implements API `Push`, which inserts stream feature values to both online store and offline store.
=> feat(pkg/oomstore): implement API Push for stream features

internal/database/dbutil/data_loader.go, internal/database/offline/bigquery/export.go, internal/database/offline/bigquery/import.go, internal/database/offline/bigquery/join.go, internal/database/offline/bigquery/store.go, internal/database/offline/mysql/store.go, internal/database/offline/postgres/store.go, internal/database/offline/postgres/util.go, internal/database/offline/redshift/store.go, internal/database/offline/snowflake/store.go, internal/database/offline/sqlite/store.go, internal/database/offline/sqlutil/create_table.go, internal/database/offline/sqlutil/export.go, internal/database/offline/sqlutil/import.go, internal/database/offline/sqlutil/join.go, internal/database/offline/sqlutil/join_helper.go, internal/database/offline/sqlutil/push.go, internal/database/offline/sqlutil/serialize.go, internal/database/offline/sqlutil/snapshot.go, internal/database/offline/sqlutil/table_schema.go
=> feat(offline): error add stack trace

internal/database/dbutil/schema.go, internal/database/offline/sqlutil/join_helper.go
This PR fixes integration tests for snowflake：add schema name `Public` before `tableName` when creating new tables.
related to #894
=> feat(database): add `Public` before tableName for snowflake

internal/database/offline/sqlutil/join.go, internal/database/offline/sqlutil/join_helper.go, internal/database/offline/test_impl/join.go
This PR fixes `ReadJoinedTable`, make sure each row contains all joined values.
=> Join/fix `ReadJoinedTable`

internal/database/offline/bigquery/store_test.go, internal/database/offline/sqlutil/export.go, internal/database/offline/sqlutil/export_helper.go, internal/database/offline/test_impl/export.go
This PR modifies offline method `Export` to make it support streaming features.
TODO:
related to #802
=> Jinghan/modify offline method `Export`

pkg/oomstore/cache.go, pkg/oomstore/oomstore.go
=> fix(oomstore): stream push processor not exit graceful

internal/database/offline/sqlutil/join_helper.go, pkg/oomstore/join.go, pkg/oomstore/join_test.go
=> Fix stream join

pkg/oomstore/apply.go
=> fix(apply): multi connect write one db file at same time

pkg/oomstore/snapshot.go
=> fix(oomstore/snapshot): fix first snapshot panic

internal/database/dbutil/schema.go
=> fix(database/pg): fix duplicate index

pkg/oomstore/snapshot.go
=> chore(oomsotre/snapshot): fix feature not assgin to snapshotOpt

internal/database/offline/bigquery/export.go, internal/database/offline/bigquery/store_test.go, internal/database/offline/sqlutil/export.go, internal/database/offline/sqlutil/export_helper.go, pkg/oomstore/types/feature.go
This PR implements bigquery's method `Export`.
related to #962
=> Jinghan/implement bigquery `Export`

internal/database/offline/sqlutil/export.go, internal/database/offline/sqlutil/export_helper.go, pkg/oomstore/export.go
This PR does:
- check `FeatureNames` are all valid features for `Export`
- add `LIMIT` for offline method `Export`
=> Jinghan/fix API Export

internal/database/metadata/mysql/db_test.go, internal/database/metadata/mysql/group.go, internal/database/metadata/mysql/schema.go, internal/database/metadata/postgres/db_test.go, internal/database/metadata/postgres/group.go, internal/database/metadata/postgres/schema.go, internal/database/metadata/sqlite/db_test.go, internal/database/metadata/sqlite/group.go, internal/database/metadata/sqlite/schema.go, internal/database/metadata/sqlutil/group.go, internal/database/metadata/test_impl/group.go, internal/database/metadata/types.go, oomagent/test/data/user_click.yaml, oomcli/cmd/register_group.go, oomcli/cmd/types.go, oomcli/test/test_apply_entity.sh, oomcli/test/test_apply_group.sh, oomcli/test/test_get_meta_entity.sh, oomcli/test/test_get_meta_group.sh, oomcli/test/test_update_group.sh, pkg/oomstore/apply.go, pkg/oomstore/apply_test.go, pkg/oomstore/group.go, pkg/oomstore/types/apply/apply.go, pkg/oomstore/types/group.go, pkg/oomstore/types/options.go
this PR adds the field `snapshot_interval` for stream group.
=> Feat new field snapshotinterval

oomcli/cmd/register_group.go
current:
```
(base) ➜  oomstore git:(test/snapshot-cdc) oomcli register group -h
Register a new feature group
Usage:
oomcli register group <group_name> [flags]
Flags:
-c, --category string         group category (default "batch")
-d, --description string      group description
-e, --entity string           entity name
-h, --help                    help for group
-s, --snapshot_interval int   stream group snapshot interval (default 86400)
Global Flags:
--config string   config file (default "/Users/lianxm/.config/oomstore/config.yaml")
```
we need:
```
(base) ➜  oomstore git:(test/snapshot-cdc) ✗ oomcli register group -h             
Register a new feature group
Usage:
oomcli register group <group_name> [flags]
Flags:
-c, --category string            group category (default "batch")
-d, …
```
=> refactor(oomcli/register-group): modify argument snapshot_interval type

internal/database/offline/bigquery/store.go, internal/database/offline/mysql/store.go, internal/database/offline/postgres/store.go, internal/database/offline/redshift/store.go, internal/database/offline/snowflake/store.go, internal/database/offline/sqlite/store.go, internal/database/offline/sqlutil/create_table.go
This PR refactors offline method `sqlutil.CreateTable`: handle no index database (snowflake, bigquery, redshift).
=> Jinghan/refactor offline method `CreateTable`

pkg/oomstore/import.go, pkg/oomstore/import_stream.go, pkg/oomstore/push_processor.go, pkg/oomstore/types/import.go, pkg/oomstore/util/feature.go
This PR implements API `ImportStream`. Currently it only supports `CsvReaderDataSource`, we will add more input type in later PRs. 
=> Jinghan/implement API `ImportStream`

pkg/oomstore/import_stream.go, pkg/oomstore/types/import.go
This PR modifies API `ImportStream`: support reading from csv file.
=> feat(pkg/oomstore):  API `ImportStream` supports csv file

sdk/python_v2/Cargo.lock, sdk/python_v2/Cargo.toml, sdk/python_v2/src/lib.rs, sdk/python_v2/test/health_check.py
=> refactor(sdk/py): implement health_check api

sdk/python_v2/Makefile.toml, sdk/python_v2/examples/online_multi_get.py, sdk/python_v2/src/convert.rs, sdk/python_v2/src/lib.rs
=> feat(sdk/py): implement online multi get api

sdk/python_v2/examples/sync.py, sdk/python_v2/src/convert.rs, sdk/python_v2/src/lib.rs
=> feat(sdk/py): implement sync api

pkg/oomstore/import.go, pkg/oomstore/import_stream.go, pkg/oomstore/types/import.go, pkg/oomstore/types/types.go
This PR implements function `tableLinkImportStream`. With that, we support `table link` to bulk load historical streaming feature values.
=> Jinghan/implement `tableLinkImportStream`

sdk/python_v2/Cargo.lock, sdk/python_v2/Cargo.toml, sdk/python_v2/examples/import.py, sdk/python_v2/src/convert.rs, sdk/python_v2/src/error.rs, sdk/python_v2/src/lib.rs
=> feat(sdk/py): implement import api

sdk/python_v2/examples/push.py, sdk/python_v2/src/convert.rs, sdk/python_v2/src/lib.rs
=> feat(sdk/py): implement push api

sdk/python_v2/Makefile.toml, sdk/python_v2/examples/join.py, sdk/python_v2/src/lib.rs
=> feat(sdk/py): implement join api

sdk/python_v2/examples/export.py, sdk/python_v2/src/lib.rs
=> feat(sdk/py): implement export api

sdk/python_v2/examples/snapshot.py, sdk/python_v2/src/lib.rs
=> feat(sdk/py): implement snapshot api

internal/database/offline/bigquery/store.go, internal/database/offline/bigquery/store_test.go, internal/database/offline/mock_offline/store.go, internal/database/offline/mysql/store.go, internal/database/offline/mysql/store_test.go, internal/database/offline/postgres/store.go, internal/database/offline/postgres/store_test.go, internal/database/offline/redshift/store.go, internal/database/offline/redshift/store_test.go, internal/database/offline/snowflake/store.go, internal/database/offline/snowflake/store_test.go, internal/database/offline/sqlite/store.go, internal/database/offline/sqlite/store_test.go, internal/database/offline/sqlutil/table_schema.go, internal/database/offline/store.go, internal/database/offline/test_impl/table_schema.go, internal/database/offline/tidb/store_test.go, internal/database/offline/types.go, pkg/oomstore/import.go, pkg/oomstore/import_stream.go, pkg/oomstore/types/types.go
This PR refactors offline method `TableSchema`: add field `TimeRange`.
=> Jinghan/add `TimeRange` to offline method `TableSchema`

internal/database/offline/sqlutil/join.go, pkg/oomstore/join.go
=> fix(oomstore/join): fix panic if group revision is empty

oomagent/codegen/oomagent.pb.go, oomagent/server.go, oomagent/test/test_push.sh, oomcli/cmd/push.go, pkg/oomstore/push.go, pkg/oomstore/types/options.go, proto/oomagent.proto, sdk/python/src/oomstore/codegen/oomagent_pb2.py, sdk/python_v2/Cargo.lock, sdk/python_v2/Cargo.toml, sdk/python_v2/src/lib.rs, sdk/rust/Cargo.toml, sdk/rust/examples/push.rs, sdk/rust/proto/oomagent.proto, sdk/rust/src/lib.rs
Replace slice with map in push option
=> Refactor push opt

internal/database/online/cassandra/import.go, internal/database/online/dynamodb/import.go, internal/database/online/redis/import.go, internal/database/online/sqlutil/import.go, internal/database/online/sqlutil/purge.go, internal/database/online/store.go, internal/database/online/test_impl/get.go, internal/database/online/test_impl/purge.go, internal/database/online/test_impl/util.go, internal/database/online/types.go, pkg/oomstore/sync.go
This PR refactors offline method `Import`: support importing streaming features.
related to #1032
=> Jinghan/offline method `Import` supports streaming features

pkg/oomstore/sync.go
This PR modifies API `Sync`: support syncing streaming features from offline to online.
close #1032
=> feat(pkg/oomstore): modify API Sync, support streaming features

internal/database/metadata/informer/group.go, internal/database/metadata/informer/informer.go, internal/database/metadata/mock_metadata/store.go, internal/database/metadata/store.go, pkg/oomstore/import.go, pkg/oomstore/import_stream.go, pkg/oomstore/push_processor.go, pkg/oomstore/revision.go
This PR does:
- implement informer API `GetCachedGroup`
- use informer APIs in push processor
close #1008
=> Jinghan/implement informer API `GetCachedGroup`

internal/database/offline/sqlutil/export.go, internal/database/offline/sqlutil/join.go, internal/database/offline/types.go
This PR reorganizes helpers of offline method `Join`.
=> Jinghan/reorganize helpers of offline method `Join`

oomcli/cmd/util.go, pkg/errdefs/wrap.go
ref: https://github.com/pkg/errors/issues/75#issuecomment-574580408
=> refactor(errdefs): avoid printing multiple call stacks

internal/database/dbutil/db_opt.go, internal/database/dbutil/sql.go, internal/database/online/cassandra/store.go, internal/database/online/cassandra/store_test.go, internal/database/online/dynamodb/create_table.go, internal/database/online/dynamodb/import.go, internal/database/online/dynamodb/store.go, internal/database/online/dynamodb/store_test.go, internal/database/online/mysql/store.go, internal/database/online/postgres/store.go, internal/database/online/sqlite/store.go, internal/database/online/sqlutil/create_table.go
This PR does:
- implement `CreateTable` for dynamoDB
- add cassandra to `dbOpt`
- implement `CreateTable` for cassandra
=> Jinghan/implement `CreateTable` for dynamoDB and cassandra

internal/database/online/cassandra/store_test.go, internal/database/online/cassandra/stream.go, internal/database/online/dynamodb/store_test.go, internal/database/online/dynamodb/stream.go, internal/database/online/mock_online/store.go, internal/database/online/mysql/store.go, internal/database/online/mysql/store_test.go, internal/database/online/postgres/store.go, internal/database/online/postgres/store_test.go, internal/database/online/redis/store.go, internal/database/online/redis/store_test.go, internal/database/online/sqlite/store.go, internal/database/online/sqlite/store_test.go, internal/database/online/sqlutil/util.go, internal/database/online/store.go, internal/database/online/test_impl/create_table.go, internal/database/online/test_impl/push.go, internal/database/online/tikv/store.go, internal/database/online/tikv/store_test.go, internal/database/online/types.go, pkg/oomstore/apply.go, pkg/oomstore/feature.go, pkg/oomstore/group.go
This PR replaces `PrepareStreamTable` by `CreateTable` in the codebase.
=> Jinghan/replace `PrepareStreamTable` by `CreateTable`

internal/database/offline/bigquery/join.go, internal/database/offline/bigquery/store.go, internal/database/offline/bigquery/table_schema.go, internal/database/offline/snowflake/store_test.go, internal/database/offline/sqlutil/join.go, internal/database/offline/test_impl/table_schema.go, pkg/oomstore/import_stream.go, pkg/oomstore/types/types.go
This PR does:
- query entity rows table, get `min_unix_milli` and `max_unix_milli`
- use the time range to filter out unnecessary revision ranges in `Join`
=> Jinghan/improve Join

oomagent/server.go
=> fix(oomagent/join): fix deadlock

sdk/python_v2/pyproject.toml
https://github.com/PyO3/pyo3#usage
=> feat: only support py3.7+ to match pyo3

internal/database/offline/sqlutil/join.go
This PR adds a helper `validateJoinOpt` to check if `features` and `revisionRanges` are valid.
=> refactor(database/offline): add helper validateJoinOpt

oomagent/test/test_channel_export.sh, oomagent/test/test_channel_join.sh, oomcli/cmd/push.go, oomcli/test/test_export.sh, oomcli/test/test_join.sh, oomcli/test/test_push.sh
=> refactor: rename --features to --feature

internal/database/dbutil/util.go, internal/database/metadata/mysql/revision.go, internal/database/metadata/postgres/revision.go, internal/database/metadata/sqlite/revision.go, internal/database/metadata/test_impl/revision.go, oomcli/test/test_get_meta_revision.sh, oomcli/test/test_import_table_link.sh, pkg/oomstore/import.go, pkg/oomstore/revision.go
This PR does:
- add `snapshot` to batch feature snapshot table name
- differentiate batch and streaming feature when creating dummy snapshot table
=> Jinghan/create batch feature's dummy snapshot table

go.mod, go.sum, pkg/oomstore/types/apply/apply.go, pkg/oomstore/types/apply/entity.json, pkg/oomstore/types/apply/feature.json, pkg/oomstore/types/apply/group.json, pkg/oomstore/types/apply/validate.go
implement #1098 
TODO:
1. time.Duration type
2. references outside the schema for nesting data structures
=> feat(json-schema): validate config to apply with jsonschema

oomcli/test/test_get_meta_revision.sh, pkg/oomstore/revision.go
=> refactor: shorter dummy revision description

pkg/oomstore/import.go, pkg/oomstore/import_batch.go, pkg/oomstore/import_stream.go, pkg/oomstore/types/import.go
This PR unifies API `Import` and `ImportStream`. Now, `Import` API supports importing both batch and streaming features.
=> Jinghan/unify API `Import` and `ImportStream`

oomcli/cmd/get_meta_revision.go, oomcli/cmd/types.go
This PR adds field `CdcTable` to function `parseTokenLists`.
=> feat(oomcli/cmd): add CdcTable to parseTokenLists

pkg/oomstore/feature.go, pkg/oomstore/types/feature.go, pkg/oomstore/types/revision_test.go, pkg/oomstore/types/value_type.go
This PR does:
- add unit test for `RevisionList.Before`
- fix typo
=> Jinghan/add unit test for `RevisionList.Before`

oomagent/server.go
This PR modifes rpc `Import`: use user-defined `delimiter`.
=> feat(oomagent): use user-defined delimiter in `Import` rpc

pkg/oomstore/apply.go, pkg/oomstore/entity.go, pkg/oomstore/import.go, pkg/oomstore/import_batch.go, pkg/oomstore/import_stream.go, pkg/oomstore/oomstore.go, pkg/oomstore/push_processor.go, pkg/oomstore/revision.go, pkg/oomstore/snapshot.go
This PR adds comments for oomstore APIs and helper functions.
=> doc(pkg/oomstore): add comments for oomstore APIs and functions

pkg/oomstore/sync.go
=> fix(oomstore/sync): fix sync stream feature

pkg/oomstore/export.go, pkg/oomstore/join.go, pkg/oomstore/online_query.go, pkg/oomstore/types/feature.go
This PR adds a few methods to `types.FeatureList`, deprecates a few ad-hoc helper functions.
=> Jinghan/add methods to `types.FeatureList`

internal/database/online/dynamodb/import.go, internal/database/online/redis/import.go, internal/database/online/sqlutil/import.go, internal/database/online/tikv/import.go
=> fix(online/import): fix importOpt.ExportError check

oomcli/cmd/edit_entity.go, oomcli/cmd/edit_group.go, oomcli/cmd/get_meta_entity.go, oomcli/cmd/get_meta_group.go, pkg/oomstore/entity.go, pkg/oomstore/group.go, pkg/oomstore/types/entity.go, pkg/oomstore/types/options.go
This PR does:
- refactor oomstore API `ListEntity`: add option `ListEntityOpt` and update callers
- refactor oomstore API `ListGroup`: add option `ListGroupOpt` and update callers
=> Jinghan/refactor API `ListEntity` and `ListGroup`

internal/database/metadata/sqlutil/feature.go, internal/database/metadata/test_impl/feature.go, internal/database/metadata/test_impl/helper.go, internal/database/metadata/types.go, pkg/oomstore/apply.go, pkg/oomstore/feature.go, pkg/oomstore/import.go, pkg/oomstore/revision.go, pkg/oomstore/snapshot.go
This PR modifies metadata method `ListFeature`: 
- change option `EntityID` to `EntityIDs`
- change option `GroupID` to `GroupIDs`
This change will be used in later PRs to serve more situations.
=> Jinghan/modify metadata method `ListFeature`

oomcli/cmd/edit_entity.go, oomcli/cmd/edit_feature.go, oomcli/cmd/edit_group.go, oomcli/cmd/get_meta_entity.go, oomcli/cmd/get_meta_feature.go, oomcli/cmd/get_meta_group.go, oomcli/cmd/util.go, pkg/oomstore/feature.go, pkg/oomstore/sync.go, pkg/oomstore/types/apply/apply.go, pkg/oomstore/types/apply/validate.go, pkg/oomstore/types/apply/validate_test.go, pkg/oomstore/types/group.go, pkg/oomstore/types/options.go
This PR does:
- refactor oomstore API `ListFeature`: change option `EntityName` to `EntityNames`, `GroupName` to `GroupNames`
- refactor oomcli commands `get_meta_entity/group/feature`: optimize fetching functions
- rename helper functions
=> Jinghan/refactor API `ListFeature`

internal/database/offline/bigquery/export.go, internal/database/offline/sqlutil/export.go, oomagent/server.go, oomcli/cmd/export_helper.go, pkg/oomstore/export.go, pkg/oomstore/sync.go
=> refactor(offline/import): refactor offline export with context for avoid goroutine leck

internal/database/dbutil/database.go, internal/database/offline/sqlutil/push.go, internal/database/online/sqlutil/get.go
This PR modifies helper function `IsTableNotFoundError`: add error for the unsupported backend.
=> feat(database): add error for unsupported backend in `IsTableNotFoundError`

internal/database/offline/sqlutil/import.go, internal/database/offline/test_impl/import.go, internal/database/offline/test_impl/util.go, internal/database/offline/types.go, pkg/oomstore/import_batch.go
This PR modifies `offline.ImportOpt`'s field: `NoPK` -> `Category`, make it easier to understand.
=> Jinghan/modify field of `ImportOpt`

internal/database/dbutil/schema.go, internal/database/dbutil/schema_test.go, internal/database/offline/sqlutil/create_table.go, internal/database/offline/sqlutil/import.go, internal/database/online/sqlutil/create_table.go, internal/database/online/sqlutil/import.go
This PR modifies helper function `BuildTableSchema`: aggregate its parameters to `BuildTableSchemaParams`.
=> Jinghan/aggregate params of `BuildTableSchema`

internal/database/dbutil/db_opt.go, internal/database/dbutil/type_mapping.go
=> fix(dbutil): function DBValueType support TIDB

oomagent/root.go, oomcli/cmd/edit.go, oomcli/cmd/root.go, pkg/oomstore/join.go
see: https://stackoverflow.com/questions/52320708/how-to-handle-gosec-linter-warning-potential-file-inclusion-via-variable
=> refactor: eliminate the potential file inclusion via variable
